# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1ae91e2bb5a30cf4186e2ad47b5b55eba3614d94d5ce01d8ce6ab0a11b2cd355b3f365c4adc775e8db82ad0b8ca12e6b7bd2e80141020e54f1c50aabaf428e8

test:
  secret_key_base: 3101f178fc9d61b33b936206b1669b89df9b479fa765a1610321123a8fa75d7b108347cb429836d440fb96908ef529d123a1611c82f8f25f098d13b48a0c43cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
